### ISSUE TITLE
Change LICENSE to LGPL, MPL, or a permissive license

### ISSUE THREAD

**Issue by CountBleck** [tomphttp/bare-server-node#10]
A strongly copyleft license like the GPL prevents permissively licensed projects from "linking against" `bare-server-node`.

At the same time, since `bare-server-node` uses the GPL (and not the AGPL), network use is thankfully *not* distribution. This means a GPL-licensed server/backend using `bare-server-node` does not need to disclose its source to the public. It will need to disclose its source to whoever deploys it, however.

Using MPL or LGPL would allow `bare-server-node` to be used in proprietary projects while still ensuring modifications to `bare-server-node` are disclosed upon distribution. A permissive license would additionally allow modifications to `bare-server-node` to be proprietary, which might also be desired.

The end goal of this issue is to allow proprietary or permissively-licensed backends/servers to use `bare-server-node` without needing to be licensed under the GPL.

**Comment by cloverdata** [comment]
BUMP

**Comment by e9x** [comment]
Due to personal preference and this license giving other developers more of a reason to make their own implementations, this won't happen.

However, you can use a different implementation of the Bare server or make your own.

See the [list of implementations](https://github.com/tomphttp/implementations/blob/master/README.md).
