### ISSUE TITLE
How to change system language

### ISSUE THREAD

**Issue by allmors** [tomphttp/bare-server-node#7]
When I deploy on a server in Japan, access to Google and everything is in Japanese, and when I deploy in the United States, Google searches are in English, how do I specify the language without judging by the location of the server？

**Comment by CountBleck** [comment]
That is not a bug in the bare server. Google initially chooses what language to use based on the IP address.

On an unrelated note, you should deploy in the US anyway, because the closer the server is to your users, the less latency there is. That's assuming you're in the US, of course. If your users were in Japan, I don't think you would be complaining.

Regardless, the bare server can't fix this, because the websites themselves are choosing what language to serve, and if that decision is based on the IP address, the only way to fix it is to host on a server in the US.

This issue should be closed.

**Comment by allmors** [comment]
> That is not a bug in the bare server. Google initially chooses what language to use based on the IP address.
> 
> On an unrelated note, you should deploy in the US anyway, because the closer the server is to your users, the less latency there is. That's assuming you're in the US, of course. If your users were in Japan, I don't think you would be complaining.
> 
> Regardless, the bare server can't fix this, because the websites themselves are choosing what language to serve, and if that decision is based on the IP address, the only way to fix it is to host on a server in the US.
> 
> This issue should be closed.

The problem is that I use someone else's web proxy and he will automatically set it according to my system language, not according to IP, your answer is not rigorous enough
